"""initial schema — canonical schema creation.

Revision ID: e63418b90903
Revises: None
Create Date: 2026-09-08 11:29:33.521405

This migration creates the complete current schema.

FRESH DATABASE:
    alembic upgrade head

EXISTING PRODUCTION DATABASE:
    alembic stamp e63418b90903

DO NOT run this migration against an existing production database
that already contains tables.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63418b90903'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('billing_provider', sa.String(length=30), nullable=True),
    sa.Column('billing_customer_id', sa.String(length=100), nullable=True),
    sa.Column('billing_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('billing_price_id', sa.String(length=100), nullable=True),
    sa.Column('billing_period_months', sa.Integer(), nullable=False),
    sa.Column('subscription_status', sa.String(length=30), nullable=True),
    sa.Column('pending_plan', sa.String(length=30), nullable=True),
    sa.Column('pending_billing_period_months', sa.Integer(), nullable=True),
    sa.Column('pending_plan_effective_at', sa.DateTime(), nullable=True),
    sa.Column('pending_plan_prepared_at', sa.DateTime(), nullable=True),
    sa.Column('billing_last_event_id', sa.String(length=100), nullable=True),
    sa.Column('billing_last_event_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('auto_renew_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('external_auth_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_auth_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('google_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_google_connection_org')
    )
    op.create_index(op.f('ix_google_connections_organization_id'), 'google_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_google_connections_user_id'), 'google_connections', ['user_id'], unique=False)
    op.create_table('google_oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_token', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_oauth_states_expires_at'), 'google_oauth_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_google_oauth_states_organization_id'), 'google_oauth_states', ['organization_id'], unique=False)
    op.create_index(op.f('ix_google_oauth_states_state_token'), 'google_oauth_states', ['state_token'], unique=True)
    op.create_index(op.f('ix_google_oauth_states_used'), 'google_oauth_states', ['used'], unique=False)
    op.create_index(op.f('ix_google_oauth_states_user_id'), 'google_oauth_states', ['user_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('external_data_source_id', sa.String(length=150), nullable=True),
    sa.Column('external_status', sa.String(length=30), server_default='pending', nullable=True),
    sa.Column('external_last_error', sa.Text(), nullable=True),
    sa.Column('provisioning_stage', sa.String(length=50), nullable=True),
    sa.Column('provisioning_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provisioning_stage_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_organization_id'), 'knowledge_bases', ['organization_id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('all_stores', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_status'), 'organization_invitations', ['status'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('all_stores', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization_membership')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('shopify_domain', sa.String(length=255), nullable=True),
    sa.Column('active_since', sa.DateTime(), nullable=True),
    sa.Column('keep_on_pending_downgrade', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_store_org_slug')
    )
    op.create_index(op.f('ix_stores_organization_id'), 'stores', ['organization_id'], unique=False)
    op.create_table('agent_knowledge_bases',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'knowledge_base_id')
    )
    op.create_table('agent_stores',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'store_id')
    )
    op.create_table('automation_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'store_id', 'name', name='uq_flow_org_store_name')
    )
    op.create_index(op.f('ix_automation_flows_organization_id'), 'automation_flows', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automation_flows_status'), 'automation_flows', ['status'], unique=False)
    op.create_index(op.f('ix_automation_flows_store_id'), 'automation_flows', ['store_id'], unique=False)
    op.create_table('automations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('conditions_json', sa.Text(), nullable=False),
    sa.Column('actions_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'store_id', 'name', name='uq_automation_org_store_name')
    )
    op.create_index(op.f('ix_automations_organization_id'), 'automations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automations_store_id'), 'automations', ['store_id'], unique=False)
    op.create_index(op.f('ix_automations_trigger_type'), 'automations', ['trigger_type'], unique=False)
    op.create_table('commerce_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_store_url', sa.String(length=500), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_store_url', name='uq_commerce_provider_store_url'),
    sa.UniqueConstraint('store_id', name='uq_commerce_connection_store')
    )
    op.create_index(op.f('ix_commerce_connections_organization_id'), 'commerce_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commerce_connections_provider'), 'commerce_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_commerce_connections_status'), 'commerce_connections', ['status'], unique=False)
    op.create_index(op.f('ix_commerce_connections_store_id'), 'commerce_connections', ['store_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('unread', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversations_store_id'), 'conversations', ['store_id'], unique=False)
    op.create_table('customer_store_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=150), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_order_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'store_id', name='uq_customer_store')
    )
    op.create_index(op.f('ix_customer_store_profiles_customer_id'), 'customer_store_profiles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_store_profiles_organization_id'), 'customer_store_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customer_store_profiles_store_id'), 'customer_store_profiles', ['store_id'], unique=False)
    op.create_table('dropi_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('external_store_id', sa.String(length=255), nullable=True),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('api_token_encrypted', sa.Text(), nullable=False),
    sa.Column('webhook_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', name='uq_dropi_connection_store'),
    sa.UniqueConstraint('webhook_token', name='uq_dropi_webhook_token')
    )
    op.create_index(op.f('ix_dropi_connections_organization_id'), 'dropi_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dropi_connections_status'), 'dropi_connections', ['status'], unique=False)
    op.create_index(op.f('ix_dropi_connections_store_id'), 'dropi_connections', ['store_id'], unique=True)
    op.create_index(op.f('ix_dropi_connections_webhook_token'), 'dropi_connections', ['webhook_token'], unique=True)
    op.create_table('knowledge_base_stores',
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_base_id', 'store_id')
    )
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ingestion_job_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_name', sa.String(length=500), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=30), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('external_mime_type', sa.String(length=255), nullable=True),
    sa.Column('external_modified_at', sa.DateTime(), nullable=True),
    sa.Column('parent_source_id', sa.Integer(), nullable=True),
    sa.Column('external_size', sa.BigInteger(), nullable=True),
    sa.Column('sync_generation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_source_id'], ['knowledge_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_knowledge_base_id'), 'knowledge_sources', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_organization_id'), 'knowledge_sources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_parent_source_id'), 'knowledge_sources', ['parent_source_id'], unique=False)
    op.create_table('membership_stores',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'store_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('shopify_order_id', sa.String(length=100), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('financial_status', sa.String(length=50), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('shopify_draft_order_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('external_creation_status', sa.String(length=30), nullable=True),
    sa.Column('external_last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'shopify_order_id', name='uq_order_store_shopify_id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_organization_id'), 'orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_index('uq_order_store_idempotency_key', 'orders', ['store_id', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    op.create_index('uq_order_store_shopify_draft_order_id', 'orders', ['store_id', 'shopify_draft_order_id'], unique=True, postgresql_where='shopify_draft_order_id IS NOT NULL')
    op.create_table('organization_invitation_stores',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['organization_invitations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id', 'store_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shopify_product_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'shopify_product_id', name='uq_product_store_shopify_id')
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_table('shopify_oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_oauth_states_expires_at'), 'shopify_oauth_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shopify_oauth_states_organization_id'), 'shopify_oauth_states', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shopify_oauth_states_state'), 'shopify_oauth_states', ['state'], unique=True)
    op.create_index(op.f('ix_shopify_oauth_states_store_id'), 'shopify_oauth_states', ['store_id'], unique=False)
    op.create_index(op.f('ix_shopify_oauth_states_used'), 'shopify_oauth_states', ['used'], unique=False)
    op.create_index(op.f('ix_shopify_oauth_states_user_id'), 'shopify_oauth_states', ['user_id'], unique=False)
    op.create_table('whatsapp_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.String(length=50), nullable=False),
    sa.Column('business_account_id', sa.String(length=50), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('verify_token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id', name='uq_whatsapp_phone_number'),
    sa.UniqueConstraint('store_id', name='uq_whatsapp_connection_store')
    )
    op.create_index(op.f('ix_whatsapp_connections_organization_id'), 'whatsapp_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_connections_phone_number_id'), 'whatsapp_connections', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_connections_status'), 'whatsapp_connections', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_connections_store_id'), 'whatsapp_connections', ['store_id'], unique=True)
    op.create_table('automation_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_executions_automation_id'), 'automation_executions', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_organization_id'), 'automation_executions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_status'), 'automation_executions', ['status'], unique=False)
    op.create_index(op.f('ix_automation_executions_store_id'), 'automation_executions', ['store_id'], unique=False)
    op.create_table('automation_flow_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['automation_flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'id', name='uq_flow_version_flow_id_id'),
    sa.UniqueConstraint('flow_id', 'version_number', name='uq_flow_version_number')
    )
    op.create_index(op.f('ix_automation_flow_versions_flow_id'), 'automation_flow_versions', ['flow_id'], unique=False)
    op.create_table('automation_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['whatsapp_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'window_start', name='uq_automation_rate_limit_window')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('delivery_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'provider', 'external_message_id', name='uq_message_provider_external')
    )
    op.create_index(op.f('ix_messages_agent_id'), 'messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shopify_variant_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('inventory_quantity', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'shopify_variant_id', name='uq_variant_product_shopify_id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_table('whatsapp_message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_connection_id', sa.Integer(), nullable=False),
    sa.Column('provider_template_id', sa.String(length=255), nullable=True),
    sa.Column('provider_template_name', sa.String(length=512), nullable=False),
    sa.Column('language_code', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_connection_id'], ['whatsapp_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_connection_id', 'provider_template_name', 'language_code', name='uq_whatsapp_template_connection_name_language')
    )
    op.create_index(op.f('ix_whatsapp_message_templates_organization_id'), 'whatsapp_message_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_message_templates_status'), 'whatsapp_message_templates', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_message_templates_whatsapp_connection_id'), 'whatsapp_message_templates', ['whatsapp_connection_id'], unique=False)
    op.create_table('automation_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('automation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('audience_type', sa.String(length=20), nullable=False),
    sa.Column('audience_filters', sa.JSON(), nullable=False),
    sa.Column('schedule_type', sa.String(length=30), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('send_window_start', sa.String(length=5), nullable=True),
    sa.Column('send_window_end', sa.String(length=5), nullable=True),
    sa.Column('cooldown_days', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('message_mode', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_template_id', sa.Integer(), nullable=True),
    sa.Column('template_variables', sa.JSON(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('execution_enabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_template_id'], ['whatsapp_message_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'store_id', 'name', name='uq_campaign_org_store_name')
    )
    op.create_index(op.f('ix_automation_campaigns_next_run_at'), 'automation_campaigns', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_automation_campaigns_organization_id'), 'automation_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automation_campaigns_status'), 'automation_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_automation_campaigns_store_id'), 'automation_campaigns', ['store_id'], unique=False)
    op.create_table('automation_flow_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('flow_version_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_key', sa.String(length=255), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('completed_recipients', sa.Integer(), nullable=False),
    sa.Column('failed_recipients', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['automation_flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_version_id'], ['automation_flow_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_flow_runs_flow_id'), 'automation_flow_runs', ['flow_id'], unique=False)
    op.create_index(op.f('ix_automation_flow_runs_organization_id'), 'automation_flow_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automation_flow_runs_status'), 'automation_flow_runs', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('shopify_variant_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_organization_id'), 'order_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_order_items_store_id'), 'order_items', ['store_id'], unique=False)
    op.create_table('automation_audience_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automation_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('automation_id', 'customer_id', name='uq_campaign_member')
    )
    op.create_index(op.f('ix_automation_audience_members_automation_id'), 'automation_audience_members', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_audience_members_customer_id'), 'automation_audience_members', ['customer_id'], unique=False)
    op.create_table('automation_flow_recipient_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_run_id', sa.Integer(), nullable=False),
    sa.Column('flow_version_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_node_id', sa.String(length=100), nullable=True),
    sa.Column('next_action_at', sa.DateTime(), nullable=True),
    sa.Column('claim_token', sa.String(length=100), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_run_id'], ['automation_flow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_version_id'], ['automation_flow_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_run_id', 'customer_id', name='uq_flow_recipient_run_customer')
    )
    op.create_index(op.f('ix_automation_flow_recipient_executions_claim_expires_at'), 'automation_flow_recipient_executions', ['claim_expires_at'], unique=False)
    op.create_index(op.f('ix_automation_flow_recipient_executions_customer_id'), 'automation_flow_recipient_executions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_automation_flow_recipient_executions_flow_run_id'), 'automation_flow_recipient_executions', ['flow_run_id'], unique=False)
    op.create_index(op.f('ix_automation_flow_recipient_executions_next_action_at'), 'automation_flow_recipient_executions', ['next_action_at'], unique=False)
    op.create_index(op.f('ix_automation_flow_recipient_executions_status'), 'automation_flow_recipient_executions', ['status'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_key', sa.String(length=100), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('eligible_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('excluded_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automation_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('automation_id', 'run_key', name='uq_campaign_run_key')
    )
    op.create_index(op.f('ix_automation_runs_automation_id'), 'automation_runs', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_organization_id'), 'automation_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_status'), 'automation_runs', ['status'], unique=False)
    op.create_table('automation_node_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_recipient_execution_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_recipient_execution_id'], ['automation_flow_recipient_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_node_executions_flow_recipient_execution_id'), 'automation_node_executions', ['flow_recipient_execution_id'], unique=False)
    op.create_index(op.f('ix_automation_node_executions_node_id'), 'automation_node_executions', ['node_id'], unique=False)
    op.create_table('automation_recipient_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=50), nullable=True),
    sa.Column('rendered_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('template_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'customer_id', name='uq_campaign_run_customer')
    )
    op.create_index(op.f('ix_automation_recipient_executions_customer_id'), 'automation_recipient_executions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_automation_recipient_executions_lease_expires_at'), 'automation_recipient_executions', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_automation_recipient_executions_next_attempt_at'), 'automation_recipient_executions', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_automation_recipient_executions_run_id'), 'automation_recipient_executions', ['run_id'], unique=False)
    op.create_table('automation_delivery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_execution_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_execution_id'], ['automation_recipient_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_delivery_attempts_recipient_execution_id'), 'automation_delivery_attempts', ['recipient_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_delivery_attempts_recipient_execution_id'), table_name='automation_delivery_attempts')
    op.drop_table('automation_delivery_attempts')
    op.drop_index(op.f('ix_automation_recipient_executions_run_id'), table_name='automation_recipient_executions')
    op.drop_index(op.f('ix_automation_recipient_executions_next_attempt_at'), table_name='automation_recipient_executions')
    op.drop_index(op.f('ix_automation_recipient_executions_lease_expires_at'), table_name='automation_recipient_executions')
    op.drop_index(op.f('ix_automation_recipient_executions_customer_id'), table_name='automation_recipient_executions')
    op.drop_table('automation_recipient_executions')
    op.drop_index(op.f('ix_automation_node_executions_node_id'), table_name='automation_node_executions')
    op.drop_index(op.f('ix_automation_node_executions_flow_recipient_execution_id'), table_name='automation_node_executions')
    op.drop_table('automation_node_executions')
    op.drop_index(op.f('ix_automation_runs_status'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_organization_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_automation_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_automation_flow_recipient_executions_status'), table_name='automation_flow_recipient_executions')
    op.drop_index(op.f('ix_automation_flow_recipient_executions_next_action_at'), table_name='automation_flow_recipient_executions')
    op.drop_index(op.f('ix_automation_flow_recipient_executions_flow_run_id'), table_name='automation_flow_recipient_executions')
    op.drop_index(op.f('ix_automation_flow_recipient_executions_customer_id'), table_name='automation_flow_recipient_executions')
    op.drop_index(op.f('ix_automation_flow_recipient_executions_claim_expires_at'), table_name='automation_flow_recipient_executions')
    op.drop_table('automation_flow_recipient_executions')
    op.drop_index(op.f('ix_automation_audience_members_customer_id'), table_name='automation_audience_members')
    op.drop_index(op.f('ix_automation_audience_members_automation_id'), table_name='automation_audience_members')
    op.drop_table('automation_audience_members')
    op.drop_index(op.f('ix_order_items_store_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_organization_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_automation_flow_runs_status'), table_name='automation_flow_runs')
    op.drop_index(op.f('ix_automation_flow_runs_organization_id'), table_name='automation_flow_runs')
    op.drop_index(op.f('ix_automation_flow_runs_flow_id'), table_name='automation_flow_runs')
    op.drop_table('automation_flow_runs')
    op.drop_index(op.f('ix_automation_campaigns_store_id'), table_name='automation_campaigns')
    op.drop_index(op.f('ix_automation_campaigns_status'), table_name='automation_campaigns')
    op.drop_index(op.f('ix_automation_campaigns_organization_id'), table_name='automation_campaigns')
    op.drop_index(op.f('ix_automation_campaigns_next_run_at'), table_name='automation_campaigns')
    op.drop_table('automation_campaigns')
    op.drop_index(op.f('ix_whatsapp_message_templates_whatsapp_connection_id'), table_name='whatsapp_message_templates')
    op.drop_index(op.f('ix_whatsapp_message_templates_status'), table_name='whatsapp_message_templates')
    op.drop_index(op.f('ix_whatsapp_message_templates_organization_id'), table_name='whatsapp_message_templates')
    op.drop_table('whatsapp_message_templates')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_agent_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('automation_rate_limits')
    op.drop_index(op.f('ix_automation_flow_versions_flow_id'), table_name='automation_flow_versions')
    op.drop_table('automation_flow_versions')
    op.drop_index(op.f('ix_automation_executions_store_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_status'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_organization_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_automation_id'), table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index(op.f('ix_whatsapp_connections_store_id'), table_name='whatsapp_connections')
    op.drop_index(op.f('ix_whatsapp_connections_status'), table_name='whatsapp_connections')
    op.drop_index(op.f('ix_whatsapp_connections_phone_number_id'), table_name='whatsapp_connections')
    op.drop_index(op.f('ix_whatsapp_connections_organization_id'), table_name='whatsapp_connections')
    op.drop_table('whatsapp_connections')
    op.drop_index(op.f('ix_shopify_oauth_states_user_id'), table_name='shopify_oauth_states')
    op.drop_index(op.f('ix_shopify_oauth_states_used'), table_name='shopify_oauth_states')
    op.drop_index(op.f('ix_shopify_oauth_states_store_id'), table_name='shopify_oauth_states')
    op.drop_index(op.f('ix_shopify_oauth_states_state'), table_name='shopify_oauth_states')
    op.drop_index(op.f('ix_shopify_oauth_states_organization_id'), table_name='shopify_oauth_states')
    op.drop_index(op.f('ix_shopify_oauth_states_expires_at'), table_name='shopify_oauth_states')
    op.drop_table('shopify_oauth_states')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('organization_invitation_stores')
    op.drop_index('uq_order_store_shopify_draft_order_id', table_name='orders', postgresql_where='shopify_draft_order_id IS NOT NULL')
    op.drop_index('uq_order_store_idempotency_key', table_name='orders', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_organization_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('membership_stores')
    op.drop_index(op.f('ix_knowledge_sources_parent_source_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_organization_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_knowledge_base_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_table('knowledge_base_stores')
    op.drop_index(op.f('ix_dropi_connections_webhook_token'), table_name='dropi_connections')
    op.drop_index(op.f('ix_dropi_connections_store_id'), table_name='dropi_connections')
    op.drop_index(op.f('ix_dropi_connections_status'), table_name='dropi_connections')
    op.drop_index(op.f('ix_dropi_connections_organization_id'), table_name='dropi_connections')
    op.drop_table('dropi_connections')
    op.drop_index(op.f('ix_customer_store_profiles_store_id'), table_name='customer_store_profiles')
    op.drop_index(op.f('ix_customer_store_profiles_organization_id'), table_name='customer_store_profiles')
    op.drop_index(op.f('ix_customer_store_profiles_customer_id'), table_name='customer_store_profiles')
    op.drop_table('customer_store_profiles')
    op.drop_index(op.f('ix_conversations_store_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_commerce_connections_store_id'), table_name='commerce_connections')
    op.drop_index(op.f('ix_commerce_connections_status'), table_name='commerce_connections')
    op.drop_index(op.f('ix_commerce_connections_provider'), table_name='commerce_connections')
    op.drop_index(op.f('ix_commerce_connections_organization_id'), table_name='commerce_connections')
    op.drop_table('commerce_connections')
    op.drop_index(op.f('ix_automations_trigger_type'), table_name='automations')
    op.drop_index(op.f('ix_automations_store_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_organization_id'), table_name='automations')
    op.drop_table('automations')
    op.drop_index(op.f('ix_automation_flows_store_id'), table_name='automation_flows')
    op.drop_index(op.f('ix_automation_flows_status'), table_name='automation_flows')
    op.drop_index(op.f('ix_automation_flows_organization_id'), table_name='automation_flows')
    op.drop_table('automation_flows')
    op.drop_table('agent_stores')
    op.drop_table('agent_knowledge_bases')
    op.drop_index(op.f('ix_stores_organization_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_organization_invitations_status'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_knowledge_bases_organization_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_google_oauth_states_user_id'), table_name='google_oauth_states')
    op.drop_index(op.f('ix_google_oauth_states_used'), table_name='google_oauth_states')
    op.drop_index(op.f('ix_google_oauth_states_state_token'), table_name='google_oauth_states')
    op.drop_index(op.f('ix_google_oauth_states_organization_id'), table_name='google_oauth_states')
    op.drop_index(op.f('ix_google_oauth_states_expires_at'), table_name='google_oauth_states')
    op.drop_table('google_oauth_states')
    op.drop_index(op.f('ix_google_connections_user_id'), table_name='google_connections')
    op.drop_index(op.f('ix_google_connections_organization_id'), table_name='google_connections')
    op.drop_table('google_connections')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
