"""add nuvemshop order fields

Revision ID: f6f002b05545
Revises: e63418b90903
Create Date: 2026-09-08 17:32:55.667916
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from sqlalchemy.dialects import postgresql
from alembic.runtime.migration import MigrationContext

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f6f002b05545'
down_revision: Union[str, None] = 'e63418b90903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def is_sqlite() -> bool:
    """Check if the current dialect is SQLite."""
    context = op.get_context()
    return context.dialect.name == 'sqlite'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if we're on SQLite (which doesn't support ALTER COLUMN TYPE)
    is_sqlite_db = op.get_context().dialect.name == 'sqlite'
    
    op.create_table('meta_ads_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('external_account_name', sa.String(length=500), nullable=True),
    sa.Column('account_currency', sa.String(length=10), nullable=True),
    sa.Column('account_timezone', sa.String(length=100), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=30), nullable=True),
    sa.Column('last_error_category', sa.String(length=50), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', name='uq_meta_ads_connection_store')
    )
    op.create_index(op.f('ix_meta_ads_connections_organization_id'), 'meta_ads_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meta_ads_connections_status'), 'meta_ads_connections', ['status'], unique=False)
    op.create_index(op.f('ix_meta_ads_connections_store_id'), 'meta_ads_connections', ['store_id'], unique=True)
    op.add_column('automation_campaigns', sa.Column('message_mode', sa.String(length=20), nullable=False))
    op.add_column('automation_campaigns', sa.Column('whatsapp_template_id', sa.Integer(), nullable=True))
    op.add_column('automation_campaigns', sa.Column('template_variables', sa.JSON(), nullable=False))
    op.add_column('automation_campaigns', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    op.add_column('automation_campaigns', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    op.add_column('automation_campaigns', sa.Column('execution_enabled_at', sa.DateTime(), nullable=True))
    # SQLite doesn't support ALTER COLUMN TYPE - skip for SQLite
    from alembic.runtime.migration import MigrationContext
    context = op.get_context()
    is_sqlite_db = context.dialect.name == 'sqlite'
    if not is_sqlite_db():
        op.alter_column('automation_campaigns', 'audience_filters',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=False)
        op.alter_column('automation_campaigns', 'schedule_config',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=False)
    op.create_index(op.f('ix_automation_campaigns_next_run_at'), 'automation_campaigns', ['next_run_at'], unique=False)
    op.create_foreign_key(None, 'automation_campaigns', 'whatsapp_message_templates', ['whatsapp_template_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_flow_version_flow_id_id', 'automation_flow_versions', ['flow_id', 'id'])
    op.add_column('automation_recipient_executions', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('automation_recipient_executions', sa.Column('next_attempt_at', sa.DateTime(), nullable=True))
    op.add_column('automation_recipient_executions', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.add_column('automation_recipient_executions', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    op.add_column('automation_recipient_executions', sa.Column('provider_message_id', sa.String(length=255), nullable=True))
    op.add_column('automation_recipient_executions', sa.Column('error_code', sa.String(length=50), nullable=True))
    op.add_column('automation_recipient_executions', sa.Column('error_message', sa.String(length=500), nullable=True))
    op.add_column('automation_recipient_executions', sa.Column('template_data', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_automation_recipient_executions_lease_expires_at'), 'automation_recipient_executions', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_automation_recipient_executions_next_attempt_at'), 'automation_recipient_executions', ['next_attempt_at'], unique=False)
    op.add_column('automation_runs', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('external_status', sa.String(length=30), server_default='pending', nullable=True))
    op.add_column('knowledge_bases', sa.Column('external_last_error', sa.Text(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('provisioning_stage', sa.String(length=50), nullable=True))
    op.add_column('knowledge_bases', sa.Column('provisioning_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_bases', sa.Column('provisioning_stage_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_sources', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('knowledge_sources', sa.Column('external_name', sa.String(length=500), nullable=True))
    op.add_column('knowledge_sources', sa.Column('sheet_name', sa.String(length=255), nullable=True))
    op.add_column('knowledge_sources', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('sync_status', sa.String(length=30), nullable=True))
    op.add_column('knowledge_sources', sa.Column('sync_error', sa.Text(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('external_mime_type', sa.String(length=255), nullable=True))
    op.add_column('knowledge_sources', sa.Column('external_modified_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('parent_source_id', sa.Integer(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('external_size', sa.BigInteger(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('sync_generation', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_knowledge_sources_parent_source_id'), 'knowledge_sources', ['parent_source_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_sources', 'knowledge_sources', ['parent_source_id'], ['id'], ondelete='SET NULL')
    op.add_column('messages', sa.Column('provider', sa.String(length=30), nullable=False))
    op.add_column('messages', sa.Column('external_message_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('delivery_status', sa.String(length=30), nullable=False))
    op.create_unique_constraint('uq_message_provider_external', 'messages', ['conversation_id', 'provider', 'external_message_id'])
    op.add_column('orders', sa.Column('external_order_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('source', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('invoice_url', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('shopify_draft_order_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('external_creation_status', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('external_last_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_orders_external_order_id'), 'orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_orders_payment_method'), 'orders', ['payment_method'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index('uq_order_store_idempotency_key', 'orders', ['store_id', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    op.create_index('uq_order_store_shopify_draft_order_id', 'orders', ['store_id', 'shopify_draft_order_id'], unique=True, postgresql_where='shopify_draft_order_id IS NOT NULL')
    op.drop_column('stores', 'repurchase_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('repurchase_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.drop_index('uq_order_store_shopify_draft_order_id', table_name='orders', postgresql_where='shopify_draft_order_id IS NOT NULL')
    op.drop_index('uq_order_store_idempotency_key', table_name='orders', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_method'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_order_id'), table_name='orders')
    op.drop_column('orders', 'external_last_error')
    op.drop_column('orders', 'external_creation_status')
    op.drop_column('orders', 'idempotency_key')
    op.drop_column('orders', 'shopify_draft_order_id')
    op.drop_column('orders', 'invoice_url')
    op.drop_column('orders', 'source')
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'external_order_id')
    op.drop_constraint('uq_message_provider_external', 'messages', type_='unique')
    op.drop_column('messages', 'delivery_status')
    op.drop_column('messages', 'external_message_id')
    op.drop_column('messages', 'provider')
    op.drop_constraint(None, 'knowledge_sources', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_sources_parent_source_id'), table_name='knowledge_sources')
    op.drop_column('knowledge_sources', 'sync_generation')
    op.drop_column('knowledge_sources', 'external_size')
    op.drop_column('knowledge_sources', 'parent_source_id')
    op.drop_column('knowledge_sources', 'external_modified_at')
    op.drop_column('knowledge_sources', 'external_mime_type')
    op.drop_column('knowledge_sources', 'metadata_json')
    op.drop_column('knowledge_sources', 'sync_error')
    op.drop_column('knowledge_sources', 'sync_status')
    op.drop_column('knowledge_sources', 'last_synced_at')
    op.drop_column('knowledge_sources', 'sheet_name')
    op.drop_column('knowledge_sources', 'external_name')
    op.drop_column('knowledge_sources', 'external_id')
    op.drop_column('knowledge_bases', 'provisioning_stage_started_at')
    op.drop_column('knowledge_bases', 'provisioning_started_at')
    op.drop_column('knowledge_bases', 'provisioning_stage')
    op.drop_column('knowledge_bases', 'external_last_error')
    op.drop_column('knowledge_bases', 'external_status')
    op.drop_column('automation_runs', 'scheduled_for')
    op.drop_index(op.f('ix_automation_recipient_executions_next_attempt_at'), table_name='automation_recipient_executions')
    op.drop_index(op.f('ix_automation_recipient_executions_lease_expires_at'), table_name='automation_recipient_executions')
    op.drop_column('automation_recipient_executions', 'template_data')
    op.drop_column('automation_recipient_executions', 'error_message')
    op.drop_column('automation_recipient_executions', 'error_code')
    op.drop_column('automation_recipient_executions', 'provider_message_id')
    op.drop_column('automation_recipient_executions', 'lease_expires_at')
    op.drop_column('automation_recipient_executions', 'claimed_at')
    op.drop_column('automation_recipient_executions', 'next_attempt_at')
    op.drop_column('automation_recipient_executions', 'attempt_count')
    op.drop_constraint('uq_flow_version_flow_id_id', 'automation_flow_versions', type_='unique')
    op.drop_constraint(None, 'automation_campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_automation_campaigns_next_run_at'), table_name='automation_campaigns')
    op.alter_column('automation_campaigns', 'schedule_config',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('automation_campaigns', 'audience_filters',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('automation_campaigns', 'execution_enabled_at')
    op.drop_column('automation_campaigns', 'last_run_at')
    op.drop_column('automation_campaigns', 'next_run_at')
    op.drop_column('automation_campaigns', 'template_variables')
    op.drop_column('automation_campaigns', 'whatsapp_template_id')
    op.drop_column('automation_campaigns', 'message_mode')
    op.drop_index(op.f('ix_meta_ads_connections_store_id'), table_name='meta_ads_connections')
    op.drop_index(op.f('ix_meta_ads_connections_status'), table_name='meta_ads_connections')
    op.drop_index(op.f('ix_meta_ads_connections_organization_id'), table_name='meta_ads_connections')
    op.drop_table('meta_ads_connections')
    # ### end Alembic commands ###